---
title: "Tarea 7"
author: "Andres Felipe Marroquin Martin"
date: "`r Sys.Date()`"
output: word_document
---

# Tarea 7

## Punto 1.
### Intervalo de confianza para la diferencia de medias entre Iris virginica e Iris setosa

```{r}
data(iris)
virginica <- iris$Petal.Length[101:150]
setosa <- iris$Petal.Length[1:50]
t.test(virginica, setosa, conf.level = 0.99)
```

## Punto 2.
### Intervalo de confianza para la diferencia entre proporciones

```{r}
hombres_padecen <- 250
mujeres_padecen <- 275
hombres_total <- 1000
mujeres_total <- 1000
prop.test(c(hombres_padecen, mujeres_padecen), c(hombres_total, mujeres_total), conf.level = 0.95)
```

## Punto 3.
### Intervalo de confianza para la media de la contaminación por nitrógeno

```{r}
nitrogeno <- c(4.9, 5.8, 5.9, 6.5, 5.5, 5.0, 5.6, 6.0, 5.7)
t.test(nitrogeno, conf.level = 0.99)
```

## Punto 4.
### Intervalo de confianza para la proporción de niños con radiografías normales

```{r}
ninos_normales <- 100
ninos_total <- 137
prop.test(ninos_normales, ninos_total, conf.level = 0.95)
```
